# Generated by Django 4.2.2 on 2024-02-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('admirer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('response', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('speak_from_heart', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Anon_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.anon')),
            ],
        ),
    ]
