# Generated by Django 4.2.2 on 2024-02-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_admirer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(default='76282', max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
