# Generated by Django 4.2.2 on 2024-02-10 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='core.anon')),
            ],
        ),
        migrations.AddField(
            model_name='anon',
            name='anon_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='core.response'),
        ),
    ]
