# Generated by Django 4.2.2 on 2024-02-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_anon_response_anon_anon_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anon',
            name='anon_response',
        ),
    ]
