# Generated by Django 4.2.2 on 2024-02-12 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='speak_from_heart',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
