# Generated by Django 4.2.2 on 2024-02-12 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_person_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Anon_Response',
        ),
    ]
